# Site
name: "Walter Augustine"
description: "Self improvement blog"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-109911871-1'
disqus: 'walteraugustine'
mailchimp-list: ''

# Authors
authors:
  walter:
    name: Walter Augustine
    display_name: Walter
    gravatar:
    email: walter@example.com
    web:
    twitter: https://twitter.com/realdonaldtrump
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
